/**
 * Export endpoint — POST /api/export
 *
 * Lets the app export a public-domain piece as MIDI, MusicXML or PDF and
 * share the file out.
 *
 * Copyright rule (the non-negotiable gate): export is served ONLY for
 * public-domain pieces.
 *   • When a `pieceId` is supplied we verify `is_public_domain = true` in the
 *     database — this is the authoritative check for catalogue/recognition
 *     pieces.
 *   • When the caller instead supplies raw `abc` (e.g. a transposed library
 *     copy that originates from the public-domain editor), the server cannot
 *     infer copyright from arbitrary bytes — the app is the gatekeeper there
 *     (it only ever calls this for pieces it already marks public-domain, the
 *     same rule the notation editor enforces). Callers must pass
 *     `publicDomain: true`.
 *
 * Response: the file bytes with a proper Content-Type + Content-Disposition.
 * Formats served as raw bytes so the app can save + share them directly:
 *   MIDI        → audio/midi        (generated from ABC)
 *   MusicXML    → application/vnd.recordare.musicxml+xml (generated from ABC)
 *   PDF         → application/pdf   (the existing curated source when present)
 */

import { sql } from "~/db";
import { parseAbc } from "./abc/abc-parser";
import { abcToMidiBuffer } from "./abc/abc-to-midi";
import { abcToMusicXml } from "./abc/abc-to-musicxml";
import { getS3ForExport } from "./export-s3";

export type ExportFormat = "midi" | "musicxml" | "pdf";

interface ExportRequest {
  format?: string;
  pieceId?: string;
  abc?: string;
  title?: string;
  publicDomain?: boolean;
}

const CORS_HEADERS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Accept",
};

function jsonError(status: number, message: string): Response {
  return Response.json({ success: false, error: message }, { status, headers: CORS_HEADERS });
}

/** Fetch a piece's public-domain row from the catalogue (null if not PD). */
async function loadPiece(pieceId: string): Promise<{ title: string; sheet_music_url: string | null } | null> {
  const rows = (await sql().query(
    `SELECT title, sheet_music_url FROM pieces
     WHERE id = $1 AND is_public_domain = true`,
    [pieceId],
  )) as unknown as Array<{ title: string; sheet_music_url: string | null }>;
  return rows.length > 0 ? rows[0] : null;
}

/** Serve the existing curated public-domain PDF from R2 for a piece. */
async function servePdf(pieceId: string, title: string): Promise<Response> {
  const s3 = getS3ForExport();
  if (!s3) {
    return jsonError(503, "PDF export is unavailable right now.");
  }
  try {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const bucket = process.env.R2_BUCKET_NAME || "notesnapscores";
    const obj = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: `sheets/${pieceId}.pdf` }));
    const body = obj.Body as ReadableStream | undefined;
    if (!body) {
      return jsonError(404, "No curated PDF source is available for this piece yet.");
    }
    const safeName = safeFileName(`${title || "score"}.pdf`);
    return new Response(body as unknown as BodyInit, {
      status: 200,
      headers: {
        ...CORS_HEADERS,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safeName}"`,
        "Cache-Control": "private, max-age=60",
      },
    });
  } catch (err) {
    console.error("[export] PDF fetch failed", pieceId, String(err).slice(0, 200));
    return jsonError(404, "No curated PDF source is available for this piece yet.");
  }
}

/** Returns the generated bytes for MIDI/MusicXML, or null on error. */
function generate(parsed: { title: string; abc: string }, format: ExportFormat): Uint8Array | null {
  try {
    const score = parseAbc(parsed.abc);
    if (score.events.length === 0) return null;
    if (format === "midi") return abcToMidiBuffer(score);
    return new TextEncoder().encode(abcToMusicXml(score));
  } catch {
    return null;
  }
}

export async function handleExport(req: Request): Promise<Response> {
  if (req.method !== "POST") {
    return jsonError(405, "Method not allowed. Use POST.");
  }
  let body: ExportRequest;
  try {
    body = (await req.json()) as ExportRequest;
  } catch {
    return jsonError(400, "Request body must be valid JSON.");
  }

  const format = (body.format ?? "").toLowerCase();
  if (format !== "midi" && format !== "musicxml" && format !== "pdf") {
    return jsonError(400, "format must be one of: midi, musicxml, pdf.");
  }

  const pieceId = body.pieceId?.trim();
  const abc = body.abc?.trim();
  const title = body.title?.trim() || "NoteSnap score";

  // ── Copyright gate ─────────────────────────────────────────────
  if (pieceId) {
    const piece = await loadPiece(pieceId).catch(() => null);
    if (!piece) {
      return jsonError(403, "Export is available for public-domain pieces only.");
    }
    if (format === "pdf") {
      return servePdf(pieceId, piece.title || title);
    }
    if (!abc) {
      return jsonError(400, "abc is required to generate this format.");
    }
    return serveGenerated(abc, title, format);
  }

  // No pieceId → caller-provided ABC path (app is gatekeeper, see header note).
  if (body.publicDomain !== true) {
    return jsonError(403, "Export is available for public-domain pieces only.");
  }
  if (!abc) {
    return jsonError(400, "abc is required to generate this format.");
  }
  if (format === "pdf") {
    return jsonError(409, "PDF export is available for pieces with a curated score. Use MIDI or MusicXML to share this ABC melody.");
  }
  return serveGenerated(abc, title, format);
}

function serveGenerated(abc: string, title: string, format: ExportFormat): Response {
  const bytes = generate({ title, abc }, format);
  if (!bytes) {
    return jsonError(422, "Could not convert this score — the ABC could not be parsed into notes.");
  }
  const isMidi = format === "midi";
  const mime = isMidi ? "audio/midi" : "application/vnd.recordare.musicxml+xml";
  const ext = isMidi ? "mid" : "musicxml";
  const fileName = safeFileName(`${title}.${ext}`);
  return new Response(bytes as unknown as BodyInit, {
    status: 200,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": mime,
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "private, max-age=60",
    },
  });
}

/** Normalise a value into a safe attachment filename (no path separators). */
function safeFileName(name: string): string {
  const cleaned = name
    .replace(/[^A-Za-z0-9 _.-]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
  return cleaned || "score";
}
