/**
 * pdGuitarCatalog — the FREE guitar/keyboard public-domain sheet-music batch
 * (owner-ratified 2026-09-28: keyboardists and guitarists expect free music from a
 * music app, so free *compliant* content is the trust hook; the money paths stay
 * affiliate/Pro/Family-Teacher).
 *
 * Source: Mutopia (mutopiaproject.org) — LilyPond-engraved TYPESET editions only.
 * Every field here is evidence captured from the piece's own Mutopia page:
 *   • licenseLabel / licenseHref — the copyright line Mutopia prints ('Public Domain'),
 *   • sourcePdfUrl  — the A4 PDF whose bytes were hashed (sha256/bytes below),
 *   • engravingSourceUrl — the .ly LilyPond source, i.e. PROOF the score is typeset,
 *     not a scan (a scanned edition is refused by the gate, not 'coming soon'-ed in),
 *   • typesetWith — the engraver version Mutopia reports,
 *   • pageCount / bytes / sha256 — the quality + integrity record of the hosted copy.
 *
 * NOTHING in this file may be published without passing gateGuitarSheet() in
 * `sheetLicenseGate.ts`; scripts/pdGuitarCatalog.test.ts fails the tier1 gate if any
 * entry carries a non-compliant licence, an unprovable typeset, a mistyped hash or a
 * sheet URL the app could not serve.
 *
 * HONEST COPY RULE: these are free public-domain SCORES we host ourselves — never
 * 'free tabs'. The 'find any song -> official TAB' promise is the AFFILIATE path only
 * (src/services/frontDoor.ts); the audit below fails on any 'free tab' claim in here.
 */

export interface GuitarPdPiece {
  slug: string;
  title: string;
  composer: string;
  catalog: string | null;
  style: string;
  difficulty: number;
  instrument: string;
  /** True when the catalog already has this piece (we attach the score, no new row). */
  existingCatalogPiece: boolean;
  note: string;
  sourceInfoUrl: string;
  sourcePdfUrl: string;
  engravingSourceUrl: string;
  midiUrl: string;
  licenseLabel: string;
  licenseHref: string;
  typesetWith: string;
  sha256: string;
  bytes: number;
  pageCount: number;
}

/** Audited 2026-09-28 against each piece's Mutopia page + the downloaded PDF bytes. */
export const PD_GUITAR_CATALOG: GuitarPdPiece[] = [
  {
    slug: "tarrega-lagrima",
    title: "Lágrima",
    composer: "Francisco Tárrega",
    catalog: null,
    style: "Romantic",
    difficulty: 3,
    instrument: "2 Guitars",
    existingCatalogPiece: true,
    note: "Tárrega's Lágrima; Mutopia's Public-Domain engraving is the 2-guitar arrangement (arr. J. J. Olson).",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2103",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/TarregaF/lagrima-duo/lagrima-duo-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/TarregaF/lagrima-duo/lagrima-duo.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/TarregaF/lagrima-duo/lagrima-duo.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.18.2",
    sha256: "414eaadb39241bf945045ba33dcf5bdbfc686076ecb271cf35e18c5b0bb597dc",
    bytes: 179136,
    pageCount: 1,
  },
  {
    slug: "tarrega-adelita",
    title: "Adelita",
    composer: "Francisco Tárrega",
    catalog: null,
    style: "Romantic",
    difficulty: 3,
    instrument: "2 Guitars",
    existingCatalogPiece: true,
    note: "Tárrega's Adelita; Public-Domain 2-guitar arrangement (arr. J. J. Olson).",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2102",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/TarregaF/adelita-duo/adelita-duo-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/TarregaF/adelita-duo/adelita-duo.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/TarregaF/adelita-duo/adelita-duo.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.18.2",
    sha256: "f9726669347659566f53ca60b8913d679b11a53d9972bf1d65391f147fc7fe45",
    bytes: 185095,
    pageCount: 1,
  },
  {
    slug: "tarrega-claro-de-luna",
    title: "Claro de Luna (Beethoven's Moonlight Sonata)",
    composer: "Francisco Tárrega",
    catalog: null,
    style: "Classical",
    difficulty: 5,
    instrument: "Guitar",
    existingCatalogPiece: false,
    note: "Tárrega's guitar transcription of Beethoven's Moonlight Sonata Adagio.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2074",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/TarregaF/claro-de-luna/claro-de-luna-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/TarregaF/claro-de-luna/claro-de-luna.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/TarregaF/claro-de-luna/claro-de-luna.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.18.2",
    sha256: "a4c5c174b432fe791d21b2fa30b1326753b322f3dc9ea88eaf0bb5f62652b5a0",
    bytes: 236785,
    pageCount: 4,
  },
  {
    slug: "carcassi-op59-preludes",
    title: "Preludes in Progressive Keys (Méthode complète)",
    composer: "Matteo Carcassi",
    catalog: "Op. 59",
    style: "Classical/Romantic",
    difficulty: 3,
    instrument: "Guitar",
    existingCatalogPiece: false,
    note: "Carcassi's progressive-key preludes from the Méthode complète (Ditson 1906 edition).",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=2209",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/CarcassiM/O59/CarcassiMethodPreludes/CarcassiMethodPreludes-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/CarcassiM/O59/CarcassiMethodPreludes/CarcassiMethodPreludes.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/CarcassiM/O59/CarcassiMethodPreludes/CarcassiMethodPreludes.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.18.2",
    sha256: "5047fc3dc20533eb1ad7e23b8bb285d748ca661773b8ff0b0343f8e3ba8b870b",
    bytes: 275881,
    pageCount: 7,
  },
  {
    slug: "bach-bwv997-1-prelude",
    title: "Lute Suite BWV 997: 1. Prelude",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 997",
    style: "Baroque",
    difficulty: 4,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 997 (lute/guitar) — movement 1 of 5, all five movements ingested.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=50",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-01prelude/bwv997-01prelude-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-01prelude/bwv997-01prelude.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-01prelude/bwv997-01prelude.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "b3a2bc1564d83e39169b578851b7dfad1be945a55f2eddd46b47a6a278ab7742",
    bytes: 86952,
    pageCount: 2,
  },
  {
    slug: "bach-bwv997-2-fuga",
    title: "Lute Suite BWV 997: 2. Fuga",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 997",
    style: "Baroque",
    difficulty: 6,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 997 movement 2 (fugue).",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=51",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-02fuga/bwv997-02fuga-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-02fuga/bwv997-02fuga.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-02fuga/bwv997-02fuga.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "637c86c70c3ebbc2c759f19a08fa041fe1f0a8b0e49351d068a4c6aefa4d8599",
    bytes: 113038,
    pageCount: 3,
  },
  {
    slug: "bach-bwv997-3-sarabande",
    title: "Lute Suite BWV 997: 3. Sarabande",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 997",
    style: "Baroque",
    difficulty: 5,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 997 movement 3.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=52",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-03sarabande/bwv997-03sarabande-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-03sarabande/bwv997-03sarabande.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-03sarabande/bwv997-03sarabande.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "450dbf99b133bc9e46b13dd0782b790f3d5ae0d28f7728eb4eb92c7441f1af1e",
    bytes: 72810,
    pageCount: 1,
  },
  {
    slug: "bach-bwv997-4-gigue",
    title: "Lute Suite BWV 997: 4. Gigue",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 997",
    style: "Baroque",
    difficulty: 5,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 997 movement 4.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=53",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-04gigue/bwv997-04gigue-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-04gigue/bwv997-04gigue.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-04gigue/bwv997-04gigue.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "87959afc4042785657f8a4c8d1d14ff7a2a97a9ad22e7fc4c5d246fa1f1cdb74",
    bytes: 74565,
    pageCount: 1,
  },
  {
    slug: "bach-bwv997-5-double",
    title: "Lute Suite BWV 997: 5. Double",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 997",
    style: "Baroque",
    difficulty: 5,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 997 movement 5.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=54",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-05double/bwv997-05double-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-05double/bwv997-05double.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV997/bwv997-05double/bwv997-05double.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "316922f7c3b9f3f65ee23cfa56b53e16fc4cfeae3d73361105a011a43dd048b8",
    bytes: 75020,
    pageCount: 2,
  },
  {
    slug: "bach-bwv999-prelude",
    title: "Prelude in D Minor",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 999",
    style: "Baroque",
    difficulty: 4,
    instrument: "Lute, Guitar",
    existingCatalogPiece: false,
    note: "BWV 999, the D-minor lute prelude guitarists play.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=60",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV999/Bach_Prelude_BWV999/Bach_Prelude_BWV999-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV999/Bach_Prelude_BWV999/Bach_Prelude_BWV999.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV999/Bach_Prelude_BWV999/Bach_Prelude_BWV999.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "7b05e1c07f853745167474c32ac7ac28c19fcfc17c3dd687234d415d2e51d1af",
    bytes: 64569,
    pageCount: 2,
  },
  {
    slug: "bach-bwv996-bourree",
    title: "Bourrée in E Minor",
    composer: "Johann Sebastian Bach",
    catalog: "BWV 996",
    style: "Baroque",
    difficulty: 4,
    instrument: "Lute or Lute-Harpischord (Lautenwerk)",
    existingCatalogPiece: false,
    note: "BWV 996 Bourrée — a first-rank guitar-learner piece.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=1743",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV996/bourree/bourree-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV996/bourree/bourree.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/BachJS/BWV996/bourree/bourree.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.12.3",
    sha256: "8608d3627269843951e414ba537dcfb53c92a098af38204e65903308e0950ee9",
    bytes: 52036,
    pageCount: 1,
  },
  {
    slug: "milan-pavana-2",
    title: "Pavana No. 2",
    composer: "Luis de Milán",
    catalog: null,
    style: "Renaissance",
    difficulty: 2,
    instrument: "Vihuela, Guitar",
    existingCatalogPiece: false,
    note: "Luis de Milán pavana for vihuela, played on guitar.",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=24",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/MilanL/milan-pavan2/milan-pavan2-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/MilanL/milan-pavan2/milan-pavan2.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/MilanL/milan-pavan2/milan-pavan2.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.16.1",
    sha256: "73240a401481019e6a371c3cb539fdb8b504189a79147be93e057c7aa5bcca81",
    bytes: 46170,
    pageCount: 1,
  },
  {
    slug: "sanz-preludio",
    title: "Preludio",
    composer: "Gaspar Sanz",
    catalog: null,
    style: "Baroque",
    difficulty: 2,
    instrument: "Guitar",
    existingCatalogPiece: false,
    note: "Gaspar Sanz prelude (Baroque guitar repertoire).",
    sourceInfoUrl: "https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=380",
    sourcePdfUrl: "https://www.mutopiaproject.org/ftp/SanzG/sanz-1/sanz-1-a4.pdf",
    engravingSourceUrl: "https://www.mutopiaproject.org/ftp/SanzG/sanz-1/sanz-1.ly",
    midiUrl: "https://www.mutopiaproject.org/ftp/SanzG/sanz-1/sanz-1.mid",
    licenseLabel: "Public Domain",
    licenseHref: "publicdomain",
    typesetWith: "LilyPond , version 2.18.2",
    sha256: "f37c3985e7d4e310d2b3452642a36e941f3c20e3f3ee1a45448e35d132170b86",
    bytes: 170417,
    pageCount: 1,
  },
];

