/**
 * useNotePreview.ts — the Hum-Along preview's engine (v33 slices G/D, owner
 * 10-04 option-4: docked INSIDE the take-correction editor, not a separate
 * screen).
 *
 * WHAT IT PLAYS: the USER'S OWN take, synthesized on the device from the tone
 * bank (src/services/toneBank.ts, generated by scripts/gen-tone-bank.js). It is
 * not a recording and not the original song, and the caption that says so lives
 * on the surface (takePreview.PREVIEW_ONLY_CAPTION).
 *
 * THE ONE RULE: the tempo is a PREVIEW CLOCK. `buildPreviewTimeline` maps the
 * take's real seconds onto the preview clock and the hook only ever READS the
 * notes — no edit path in this file writes to a take (the model's own
 * `PREVIEW_TEMPO_NEVER_REWRITES` flag is asserted in scripts/v33TakeEditor.test).
 *
 * The clock is a plain JS interval (no native playback engine): every tick reads
 * the elapsed preview time, fires the tones the clock has just crossed and
 * updates the cursor the staff highlights. The per-note audition
 * (`playNote`) is the editor's pitch rail — one tone, immediately.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Audio } from 'expo-av';
import { toneSourceFor } from '../services/toneBank';
import {
  PREVIEW_TEMPO_DEFAULT_PCT,
  buildPreviewTimeline,
  clampPreviewTempo,
  cursorIndexAt,
  loopBoundsMs,
  previewInstrument,
  previewStatusLine,
  stepIndex,
  type LoopBracket,
  type PreviewInstrumentId,
} from '../services/takePreview';
import type { MidiNoteEvent } from '../services/midiExport';

/** How often the preview clock is read (40 ms is smooth enough for a cursor). */
export const PREVIEW_TICK_MS = 40;

export interface NotePreview {
  /** True while the clock is running. */
  playing: boolean;
  loop: boolean;
  tempoPct: number;
  instrument: PreviewInstrumentId;
  /** The note the preview clock is inside, or null between notes. */
  cursor: number | null;
  /** The honest one-line status (never a claim the preview cannot back). */
  statusLine: string;
  noteCount: number;
  loopBracket: LoopBracket | null;
  play(): void;
  pause(): void;
  toggle(): void;
  toggleLoop(): void;
  /** Prev/next note (wraps at the ends). */
  step(dir: -1 | 1): void;
  /** Move the cursor to one note without starting the clock. */
  focus(index: number | null): void;
  setTempoPct(pct: number): void;
  setInstrument(id: PreviewInstrumentId): void;
  /** Audition ONE pitch now (the editor's pitch rail) — true when a tone played. */
  playNote(midi: number, instrumentOverride?: PreviewInstrumentId): Promise<boolean>;
  /** Back to the top of the preview. */
  stop(): void;
}

export function useNotePreview(
  notes: ReadonlyArray<MidiNoteEvent> | null | undefined,
  opts: { instrument?: PreviewInstrumentId; enabled?: boolean } = {},
): NotePreview {
  const enabled = opts.enabled ?? true;
  const [instrument, setInstrumentState] = useState<PreviewInstrumentId>(
    opts.instrument ?? previewInstrument(null).id,
  );
  const [tempoPct, setTempoState] = useState<number>(PREVIEW_TEMPO_DEFAULT_PCT);
  const [playing, setPlaying] = useState(false);
  const [loop, setLoop] = useState(false);
  const [cursor, setCursor] = useState<number | null>(null);
  const [loopBracket, setLoopBracket] = useState<LoopBracket | null>(null);

  const count = Array.isArray(notes) ? notes.length : 0;
  // The timeline is REBUILT from the take and the tempo — the take is only read.
  const timeline = useMemo(
    () => buildPreviewTimeline(notes ?? [], tempoPct),
    [notes, tempoPct],
  );
  const timelineRef = useRef(timeline);
  timelineRef.current = timeline;
  const bracketRef = useRef(loopBracket);
  bracketRef.current = loopBracket;
  const instrumentRef = useRef(instrument);
  instrumentRef.current = instrument;

  /** Loaded one-shot tones, keyed `<instrument>:<midi>` (loaded once, replayed). */
  const soundsRef = useRef<Map<string, Audio.Sound>>(new Map());
  const startedAtRef = useRef<number>(0);
  const elapsedRef = useRef<number>(0);
  const firedRef = useRef<Set<number>>(new Set());
  const cursorRef = useRef<number | null>(null);

  const playTone = useCallback(
    async (midi: number, which: PreviewInstrumentId): Promise<boolean> => {
      const source = toneSourceFor(which, midi);
      if (source === null) return false;
      const key = `${which}:${Math.round(midi)}`;
      try {
        let sound = soundsRef.current.get(key);
        if (!sound) {
          const created = await Audio.Sound.createAsync(source, {
            shouldPlay: false,
            volume: 1,
          });
          sound = created.sound;
          soundsRef.current.set(key, sound);
        }
        await sound.replayAsync();
        return true;
      } catch {
        // A tone that will not load is silent, never a crash: the surface still
        // draws the cursor, and nothing claims sound that did not play.
        return false;
      }
    },
    [],
  );

  const pause = useCallback(() => {
    setPlaying(false);
  }, []);

  const stop = useCallback(() => {
    setPlaying(false);
    elapsedRef.current = 0;
    firedRef.current = new Set();
    cursorRef.current = null;
    setCursor(null);
  }, []);

  const play = useCallback(() => {
    if (count === 0) return;
    const bracket = bracketRef.current;
    const bounds = loopBoundsMs(timelineRef.current, bracket);
    // Starting outside the bracket (or from the very top) restarts the bracket.
    if (elapsedRef.current < bounds.fromMs || elapsedRef.current >= bounds.toMs) {
      elapsedRef.current = bounds.fromMs;
      firedRef.current = new Set();
    }
    startedAtRef.current = Date.now() - elapsedRef.current;
    setPlaying(true);
  }, [count]);

  const toggle = useCallback(() => {
    if (playing) pause();
    else play();
  }, [pause, play, playing]);

  // THE PREVIEW CLOCK. Reads the elapsed preview time, fires the tones it has
  // just crossed, and moves the cursor. No take is touched here.
  useEffect(() => {
    if (!playing || !enabled) return;
    const id = setInterval(() => {
      const current = timelineRef.current;
      const bracket = bracketRef.current;
      const bounds = loopBoundsMs(current, bracket);
      let elapsed = Date.now() - startedAtRef.current;
      if (elapsed >= bounds.toMs) {
        if (bracket) {
          elapsed = bounds.fromMs;
          startedAtRef.current = Date.now() - elapsed;
          firedRef.current = new Set();
        } else {
          elapsedRef.current = 0;
          firedRef.current = new Set();
          cursorRef.current = null;
          setCursor(null);
          setPlaying(false);
          return;
        }
      }
      elapsedRef.current = elapsed;
      for (const event of current.events) {
        if (event.atMs < bounds.fromMs || event.atMs > bounds.toMs) continue;
        if (event.atMs > elapsed || firedRef.current.has(event.index)) continue;
        firedRef.current.add(event.index);
        void playTone(event.midi, instrumentRef.current);
      }
      const at = cursorIndexAt(current, elapsed);
      if (at !== cursorRef.current) {
        cursorRef.current = at;
        setCursor(at);
      }
    }, PREVIEW_TICK_MS);
    return () => clearInterval(id);
  }, [playing, enabled, playTone]);

  // A take with no notes can never pretend to play: the clock stops.
  useEffect(() => {
    if (count === 0) {
      setPlaying(false);
      cursorRef.current = null;
      setCursor(null);
    }
  }, [count]);

  // Unload every loaded tone when the surface (the editor) goes away.
  useEffect(() => {
    const sounds = soundsRef.current;
    return () => {
      for (const sound of sounds.values()) {
        void sound.unloadAsync().catch(() => undefined);
      }
      sounds.clear();
    };
  }, []);

  const step = useCallback(
    (dir: -1 | 1) => {
      const timelineNow = timelineRef.current;
      const next = stepIndex(cursorRef.current, dir, timelineNow.events.length);
      cursorRef.current = next;
      setCursor(next);
      if (next !== null) {
        const event = timelineNow.events[next];
        // Stepping auditions the note it lands on: that is the point of prev/next.
        void playTone(event.midi, instrumentRef.current);
        if (playing) {
          elapsedRef.current = event.atMs;
          startedAtRef.current = Date.now() - event.atMs;
          firedRef.current = new Set([event.index]);
        }
      }
    },
    [playTone, playing],
  );

  const focus = useCallback((index: number | null) => {
    cursorRef.current = index;
    setCursor(index);
  }, []);

  const setTempoPct = useCallback((pct: number) => {
    // PREVIEW ONLY. The percentage changes how fast the clock runs; the notes
    // are read by buildPreviewTimeline and never rewritten.
    setTempoState(clampPreviewTempo(pct));
  }, []);

  const setInstrument = useCallback((id: PreviewInstrumentId) => {
    setInstrumentState(previewInstrument(id).id);
  }, []);

  const toggleLoop = useCallback(() => {
    setLoop((current) => {
      const next = !current;
      setLoopBracket(next ? { fromIndex: 0, toIndex: Math.max(0, count - 1) } : null);
      return next;
    });
  }, [count]);

  const playNote = useCallback(
    (midi: number, instrumentOverride?: PreviewInstrumentId) =>
      playTone(midi, instrumentOverride ?? instrumentRef.current),
    [playTone],
  );

  const statusLine = previewStatusLine({
    playing,
    loop,
    noteCount: count,
    cursor,
  });

  return {
    playing,
    loop,
    tempoPct,
    instrument,
    cursor,
    statusLine,
    noteCount: count,
    loopBracket,
    play,
    pause,
    toggle,
    toggleLoop,
    step,
    focus,
    setTempoPct,
    setInstrument,
    playNote,
    stop,
  };
}
